inherit_from: .rubocop_todo.yml

AllCops:
    Exclude:
      - vendor/**/*
      - db/schema.rb
      - db/migrate/*
      - db/*
      - config/**/*
      - spec/**/*
      - bin/**/*
      - lib/**/*
    
    Rails:
      enabled: true
Style/TrailingCommaInArguments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
