default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db #追加
  #socket: /tmp/mysql.sock

development:
  <<: *default
  database: yumyumkitchen_development
  #username: root
  #password: password
  #database: docker_development
  #host: db

test:
  <<: *default
  database: yumyumkitchen_test

production:
  <<: *default
  encoding: utf8
  reconnect: false
  host: <%= Rails.application.credentials.db[:host] %>
  database: <%= Rails.application.credentials.db[:database] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
