default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: Azc29308fgsdrwr@
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: yumyumkitchen_development

test:
  <<: *default
  database: yumyumkitchen_test

production:
  <<: *default
  encoding: utf8
  reconnect: false
  host: <%= Rails.application.credentials.db[:host] %>
  database: <%= Rails.application.credentials.db[:database] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
