default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: Azc29308fgsdrwr@
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: yumyumkitchen_development

test:
  <<: *default
  database: yumyumkitchen_test

production:
    <<: *default
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOSTNAME'] %>
