default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: Azc29308fgsdrwr@
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: yumyumkitchen_development

test:
  <<: *default
  database: yumyumkitchen_test

production:
  <<: *default
  encoding: utf8
  reconnect: false
  host: yumyumkitchen-mysql.curdtmmsk3se.ap-northeast-1.rds.amazonaws.com
  database: yumyumkitchen_production
  username: root
  password: hasegawakei
